[toolchain]
anchor_version = "0.30.0"
solana_version = "1.17.0"

[features]
seeds = false
short = false

[programs.localnet]
ofund_token = "Gbq9aJu54T56uUPneuJa2KrCAYZTWx4r2uH78y4pZA7G"

[programs.devnet]
ofund_token = "Gbq9aJu54T56uUPneuJa2KrCAYZTWx4r2uH78y4pZA7G"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000
requires_bpf = false
feature_flags = ["skip-genesis-archive"]
